remitente = ""
destinatario = ""
nombreEmpleado = ""
conversacionActual = []
objetivoActual = "" #Incluye todo
objetivoEspecifico = "" #Dificultad
idVozActual = ""
urlAudioActual = ""
idEvento = ""
eventoDesencadenador = "" #CORREO / WHATSAPP / SMS
idConversacion = ""
hilo = False